### ISSUE TITLE
about ipv6

### ISSUE THREAD

**Issue by Tony-Yes** [felixonmars/vps2arch#14]
May I ask how to use this script for vps in only ipv6 environment

**Comment by chengnan049** [comment]
The only part of the script execution that involves the network is probably the download, you need an IPV4 address, maybe you can use NAT, or WARP, this is a [good article](https://p3terx.com/archives/use-cloudflare-warp-to-add-extra-ipv4-or-ipv6-network-support-to-vps-servers-for-free.html) and the author is also very good at maintaining several well-known projects

My English is not good, so I used Deepl Translate

**Comment by InDC1** [comment]
The installation can be installed normally, but the network will have problems after restarting. How to configure static ipv6? /64

**Comment by chengnan049** [comment]
> 


> The installation can be installed normally, but the network will have problems after restarting. How to configure static ipv6? /64

VNC
