### ISSUE TITLE
How to config IPv6 manually

### ISSUE THREAD

**Issue by ayaka14732** [felixonmars/vps2arch#5]
In README it says '_IPv6_ currently is not supported. If you need to use it, please configure it manually'. But it does not mention the way to config it manually.

**Comment by felixonmars** [comment]
Please refer to https://wiki.archlinux.org/index.php/systemd-networkd

Basically adding more `Address=` and `Gateway=` under the `[Network]` section in `/etc/systemd/network/default.network`.

**Comment by ayaka14732** [comment]
I can use IPv6 without configuration after running the script. Strangely, my `/etc/systemd/network/default.network` file contains no entry related to IPv6.

**Comment by felixonmars** [comment]
Your IPv6 address should have been acquired via RA then. You can verify this with the `dynamic` tag along your IPv6 address in `ip -6 a`'s output. IPv6 address acquired this way may be subjected to change and should not be the recommended setting in most scenarios.
